name: "Build IOS"

on:
  workflow_call: # Altere o trigger para workflow_call
    secrets:
      APPSTORE_ISSUER_ID:
        required: true
      APPSTORE_API_KEY_ID:
        required: true
      APPSTORE_API_PRIVATE_KEY:
        required: true
      IOS_CERTIFICATE_FILE:
        required: true
      API_KEY:
        required: true
      IOS_CERT_PASS:
        required: true
jobs:
  build-ios:
    env:
      TESTE3: "21"
      TTTT: ${{ vars.TTTT }}
      TESTE: ${{ vars.TESTE }}
      TESTE4: ${{ vars.TESTE4 }}

    runs-on: macos-latest

    steps:
      - name: Echo variables
        run: |
          echo "TTTT=${{ env.TTTT }}"
          echo "TESTE=${{ env.TESTE }}"
          echo "TESTE3=${{env.TESTE3}}"
          echo "TESTE4=${{env.TESTE4}}"

      - name: Echo variables Secrets
        run: |
          echo "APPSTORE_ISSUER_ID=${{env.APPSTORE_ISSUER_ID}}"
          echo "APPSTORE_API_KEY_ID=${{env.APPSTORE_API_KEY_ID}}"
          echo "APPSTORE_API_PRIVATE_KEY=${{env.APPSTORE_API_PRIVATE_KEY}}"
          echo "IOS_CERTIFICATE_FILE=${{ env.IOS_CERTIFICATE_FILE}}" 
          echo "API_KEY=${{ env.API_KEY}}" 
          echo "IOS_CERT_PASS=${{ env.IOS_CERT_PASS}}"
        env:
          IOS_CERT_PASS: ${{ secrets.IOS_CERT_PASS }}
          IOS_CERTIFICATE_FILE: ${{ secrets.IOS_CERTIFICATE_FILE }}
          API_KEY: ${{ secrets.API_KEY }}
          APPSTORE_ISSUER_ID: ${{ secrets.APPSTORE_ISSUER_ID }}
          APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Import code sign
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_FILE }}
          p12-password: ${{ secrets.IOS_CERT_PASS }}

      - name: Download provisioning
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: br.flutterbrasil.currencyconverter
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Listar perfis de provisionamento
        run: |
          ls ~/Library/MobileDevice/Provisioning\ Profiles/

      - uses: actions/checkout@v4

      - name: Exibir a versao atual do macOS
        run: sw_vers -productVersion

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.29.0
          channel: stable

      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Informacoes e configuracoes do Flutter
        run: flutter doctor -v

      # - name: Clean
      #   run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env
        run: |
          touch .env
          echo "TESTE=${{ env.TESTE }}" >> .env
          echo "TESTE3=${{ env.TESTE3 }}" >> .env
          cat .env

      - name: Run Build Runner
        run: dart run build_runner build -d

      # - name: Configurar provisionamento automático do Xcode
      #   run: |
      #     cd ios
      #     TEAM_ID="P3472J82HC" # Seu Team ID aqui
      #     if [ -n "$TEAM_ID" ]; then
      #       /usr/libexec/PlistBuddy -c "Add :DEVELOPMENT_TEAM string $TEAM_ID" Runner.xcodeproj/project.pbxproj
      #       /usr/libexec/PlistBuddy -c "Add :ProvisioningStyle string Automatic" Runner.xcodeproj/project.pbxproj
      #     fi

      - name: Archive iOS App
        run: |
          xcodebuild archive \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/Runner.xcarchive
      - name: Executar Build para iOS
        run: |
          flutter build ios --release --split-debug-info --obfuscate

      # - name: Upload IPA to App Store Connect
      #   run: xcrun altool --upload-app --type ios -f build/ios/*.ipa --apiKey ${{ env.APPSTORE_API_KEY_ID }} --apiIssuer ${{ env.APPSTORE_ISSUER_ID }}

      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "./build/ios/conversor_moedas.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: release-ipa
          path: build/ios/conversor_moedas.ipa
