name: "Build IOS"

on:
  workflow_call: # Altere o trigger para workflow_call

jobs:
  build-ios:
    env:
      TESTE3: "21"
    runs-on: macos-latest

    steps:
      - name: Generate gerando certificado
        run: |
          touch certificado.base64
          echo "${{ secrets.IOS_CERTIFICATE_FILE }}" >> certificado.base64
          cat certificado.base64

      - name: Import code sign
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.IOS_CERTIFICATE_FILE }}
          p12-password: ${{ secrets.IOS_CERTIFICATE_FILE }}

      - name: Download provisioning
        uses: Apple-Actions/download-provisioning-profiles@v1
        with:
          bundle-id: com.myApp.MyApp
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Exibir a versao atual do macOS
        run: sw_vers -productVersion

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.29.0
          channel: stable

      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Informacoes e configuracoes do Flutter
        run: flutter doctor -v

      - name: Clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Generate .env
        run: |
          touch .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "TESTE=${{ vars.TESTE }}" >> .env
          echo "TESTE3=${{ env.TESTE3 }}" >> .env
          cat .env

      - name: Executar Build para iOS
        run: |
          flutter build ios --release

      # - name: Upload IPA to App Store Connect
      #   run: xcrun altool --upload-app --type ios -f build/ios/*.ipa --apiKey ${{ secrets.APPSTORE_API_KEY_ID }} --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}

      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "./build/ios/conversor_moedas.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: release-ipa
          path: build/ios/conversor_moedas.ipa
