name: "Build IOS"

on:
  workflow_call: # Altere o trigger para workflow_call

jobs:
  build-ios:
    env:
      TESTE3: "21"
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Exibir a versao atual do macOS
        run: sw_vers -productVersion

      - name: Instalar o Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.29.0
          channel: stable

      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Informacoes e configuracoes do Flutter
        run: flutter doctor -v

      - name: Clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Generate .env
        run: |
          touch .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "TESTE=${{ vars.TESTE }}" >> .env
          echo "TESTE3=${{ env.TESTE3 }}" >> .env
          cat .env

      - name: Executar Build para iOS
        run: |
          flutter build ios --release

      # - name: Upload IPA to App Store Connect
      #   run: xcrun altool --upload-app --type ios -f build/ios/*.ipa --apiKey N9H98Y3LBZ --apiIssuer $(IOS_ISSUER_ID)

      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "./app.ipa"
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: release-ipa
          path: build/ios/iphonesimulator/Runner.app
