name: "Publicando Android"

on:
  workflow_call:
    secrets:
      API_KEY:
        required: true
      ANDROID_STOREPASSWORD:
        required: true
      ANDROID_KEYSTORE:
        required: true
      PLAY_AUTH_JSON:
        required: true

jobs:
  build-android:
    env:
      TESTE3: "21"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "17.x"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.14.0
        with:
          flutter-version: 3.29.2
          channel: stable

      - name: Exibir a versao instalada do Flutter
        run: flutter --version

      - name: Clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Generate .env
        run: |
          touch .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          echo "TESTE=${{ vars.TESTE }}" >> .env
          echo "TESTE3=${{ env.TESTE3 }}" >> .env
          cat .env

      - name: Run Build Runner
        run: dart run build_runner build -d

      - name: Generate keyproperties
        run: |
          cd android
          touch key.properties
          echo "storePassword=${{ secrets.ANDROID_STOREPASSWORD }}" >> key.properties
          echo "keyPassword=${{ secrets.ANDROID_STOREPASSWORD }}" >> key.properties
          echo "keyAlias=upload" >> key.properties
          echo "storeFile=./keystore.jks" >> key.properties
          cat key.properties

      - name: Generate Key Store
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
        run: echo "$ANDROID_KEYSTORE" | base64 -d >> ./android/app/keystore.jks

      - name: Statically analyze
        run: flutter analyze .

      - name: Run Tests
        run: flutter test

      - name: Build apk.
        run: flutter build apk --release

      - name: Build appBundle.
        run: flutter build appbundle --release

      - name: Print Version.
        run: |
          path_to_pubspec="pubspec.yaml"
          current_version=$(awk '/^version:/ {print $2}' $path_to_pubspec)
          current_version_without_build=$(echo "$current_version" | sed 's/\+.*//')
          echo "Generated version $current_version

      - name: Upload Artifact APK
        uses: actions/upload-artifact@main
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Artifact AAB
        uses: actions/upload-artifact@main
        with:
          name: release-aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > service_account.json

      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: service_account.json
          packageName: com.flutterbrasil.conversor_moedas
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: "internal"
          status: "completed"
          whatsNewDirectory: whatsNew/
